# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.6.2
- pip

- pip:
  - azureml-sdk==1.10.0
  - azureml-defaults>=1.0.45
  - luna-publish-utils>=0.7.3
  - pyyaml
  - inference-schema[numpy-support]
  - mlflow
  - azureml-contrib-services
  # Add pip packages used in your project
channels:
- conda-forge
