MLproject: MLproject
supported_run_mode: local,azureml,mlflow
run_mode: azureml
project_type: train_your_own_model
conda_env: conda.yml
deploy_config: .cloud/.azureml/deploy_config.yml
code:
  inference_entry_script: 'src/luna_publish/score.py'
azureml:
  run_config: .cloud/.azureml/aml_run_config.yml
  workspace_config_path: .cloud/.azureml
  workspace_config_file_name: workspace.json
mlflow:
  spark_config: .cloud/.mlflow/spark_config.json
  workspace_config: .cloud/.mlflow/compute.yml
  test_experiment: .cloud/.mlflow/test_experiment.yml